apiVersion: v1
kind: Service
metadata:
  name: health-checker-backend-service
spec:
  selector:
    app: health-checker-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
