apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checker-backend
  template:
    metadata:
      labels:
        app: health-checker-backend
    spec:
      containers:
        - name: health-checker-backend
          image: hamedfahimi/health-checker:latest
          ports:
            - containerPort: 8080
