apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker-deployment
  labels:
    app: health-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checker
  template:
    metadata:
      labels:
        app: health-checker
    spec:
      containers:
        - name: health-checker
          image: hamedfahimi/health-checker:latest
          ports:
            - containerPort: 8080
