apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checker-frontend
  template:
    metadata:
      labels:
        app: health-checker-frontend
    spec:
      containers:
        - name: health-checker-frontend
          image: hamedfahimi/health-checker-frontend:latest
          ports:
            - containerPort: 8000
