apiVersion: v1
kind: Service
metadata:
  name: health-checker-frontend-service
spec:
  selector:
    app: health-checker-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
